### PR TITLE
Gpu experiments

### PR DESCRIPTION
**Pull request by chaithyagr**
Add GPU Code to gpu branch of ModOpt to have something functional. 

These codes are used constantly for carrying out acquisition and reconstruction. It would help to keep them at `gpu` branch of mainline.

Also, with this PR, we will be sync with master (all the updated documentation)

### CODE REVIEW

**Comment by sfarrens** [comment]
@chaithyagr I can't merge this PR as it stands as there are no docstrings in the new `backend.py` module.

Do you want this included in the next PySAP release? If so, then you will need to polish it up before I make the ModOpt release. Otherwise, we can include it in a ModOpt patch and it will be included in the following PySAP release at the end of June.

**Comment by sfarrens** [comment]
Actually, it looks like this PR isn't targeting the master branch. Did you want to switch the target branch?

**Comment by chaithyagr** [comment]
> @chaithyagr I can't merge this PR as it stands as there are no docstrings in the new `backend.py` module.
> 
> Do you want this included in the next PySAP release? If so, then you will need to polish it up before I make the ModOpt release. Otherwise, we can include it in a ModOpt patch and it will be included in the following PySAP release at the end of June.

What do you want me to do? I can add the required docstrings tomorrow...

**Comment by sfarrens** [comment]
> > @chaithyagr I can't merge this PR as it stands as there are no docstrings in the new `backend.py` module.
> > Do you want this included in the next PySAP release? If so, then you will need to polish it up before I make the ModOpt release. Otherwise, we can include it in a ModOpt patch and it will be included in the following PySAP release at the end of June.
> 
> What do you want me to do? I can add the required docstrings tomorrow...

OK, if you don't mind updating this tomorrow I can include the changes into the planned v1.5 release. 🙂

**Comment by chaithyagr** [comment]
I prefer it to be merged into develop branch, so that it is in release 1.5

**Comment by sfarrens** [comment]
OK @chaithyagr I have re-implemented most of this PR in #104 and updated everything to fit the new structure. There will be some things to resolve in future issues, but if you are happy with what is in #104 then I will close this PR.

Also, do you want to keep the `gpu` branch? I think we can remove this and target `develop` for all PRs.

**Comment by chaithyagr** [comment]
Yes we can remove gpu and also close this PR. Thank you for handling this!

**Pull request closed without merging**
