### PR TITLE
added writeable input data array feature for benchopt

### LINKED ISSUE #204: [NEW FEATURE] leave possibility to keep data writeable
**Is your feature request related to a problem? Please describe.**
After calling a modopt solver on `X, y`, I can no longer call a sklearn.linear_model.Lasso on it, because modopt has made X and y not writeable. 

**Describe the solution you'd like**
The check_npdarray has a `writeable` parameter but it's not exposed at the solver level, hence I don't think the user can control it.

Code to reproduce:
```python
from benchopt.datasets.simulated import make_correlated_data
import numpy as np
from numpy.linalg import norm

from modopt.opt.algorithms import ForwardBackward
from modopt.opt.proximity import SparseThreshold
from modopt.opt.linear import Identity
from modopt.opt.gradient import GradBasic
from sklearn.linear_model import Lasso


np.random.seed(0)
X = np.random.randn(10, 20)
y = np.random.randn(X.shape[0])
lmbd = norm(X.T @ y) / 20


def op(w):
    return X @ w


fb = ForwardBackward(
    x=np.zeros(X.shape[1]),  # this is the coefficient w
    grad=GradBasic(
        input_data=y, op=op,
        trans_op=lambda res: X.T @ res,
    ),
    prox=SparseThreshold(Identity(), lmbd),
    beta_param=1.0,
    min_beta=1,
    metric_call_period=None,
    xi_restart=0.96,
    restart_strategy='adaptive-1',
    s_greedy=1.01,
    p_lazy=1,
    q_lazy=1,
    auto_iterate=False,
    progress=False,
    cost=None,
)


L = np.linalg.norm(X, ord=2) ** 2
fb.beta_param = 1 / L
fb._beta = 1 / L
fb.iterate(max_iter=100)

# this fails:
Lasso(fit_intercept=False, alpha=lmbd/len(y)).fit(X, y)
```

**Are you planning to submit a Pull Request?**
- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by sfarrens**
## Summary

- closes #204
- added `input_data_writeable` option to `GradParent`

### CODE REVIEW

**Review by chaithyagr — APPROVED** [review]
LGTM

**Comment by mathurinm** [comment]
Thanks a lot @sfarrens 

Do you already know when this will land on PyPI ?

**Comment by sfarrens** [comment]
Hi @mathurinm! We have in mind to make a PySAP release on the first week of May. Normally I tag a new release of ModOpt shortly before that. So, I would say within the next 2-3 weeks. If this is urgent, however, we can certainly release a patch a bit sooner than that.

**Comment by mathurinm** [comment]
A patch release would enable us to be done with Modopt's reintegration into benchopt : https://github.com/benchopt/benchmark_lasso/pull/45 so that'd be nice, but only if it's not too much of a hassle on your side

**Comment by sfarrens** [comment]
No problem, I can probably do it on Monday.

**Pull request merged**
